# 部署 k8s-demo
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-deployment 
  namespace: netcore
  labels:
    name: k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k8s-demo
  template:
    metadata:
      labels:
        name: k8s-demo
    spec:
      containers:
        - name: k8s-demo-api
          image: siegrainwong/k8s-demo:1.1
          ports: 
          - containerPort: 80
          imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: demo-service
  namespace: netcore
spec: 
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
  selector:
    name: k8s-demo