# 第4节教学：探针
---

kind: Deployment   # 组件类型
apiVersion: apps/v1
metadata:
  name: fucking-live # 整个deploy组件的名称，会作为部署名以及容器组跟副本集的前缀。
  namespace: netcore-probe  # 可指定，不指定时使用默认命名空间
  labels:
    name: dep-label-name  # 组件标签
spec:
  replicas: 2
  selector:
    matchLabels:
      name: netcore-api-live
  template:
    metadata:
      labels:
        name: netcore-api-live
    spec:
      containers:
        - name: netcore-k8s-demo
          image: siegrainwong/k8s-demo:latest  # docker hub 中的镜像名称
          ports: 
          - containerPort: 80
          imagePullPolicy: Always
          # liveness 探针
          livenessProbe:
            httpGet:  # 探针访问类型
              path: /api/values
              port: 80
            timeoutSeconds: 5
          # readiness 探针
          readinessProbe:
            httpGet:  # 探针访问类型
              path: /health
              port: 80
            timeoutSeconds: 5
---

kind: Service
apiVersion: v1
metadata:
  name: probesvc
  namespace: netcore-probe
spec: 
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
  selector:
    name: netcore-api-live