# 以 imagePullSecret 的形式使用 Secret
# https://cr.console.aliyun.com/cn-hangzhou/repositories 阿里云容器镜像服务

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: name-deployment
  namespace: netcore
  labels:
    name: name-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: name-api
  template:
    metadata:
      labels:
        name: name-api
    spec:
      containers:
        - name: netcore-name-api
          env: 
            - name: POD_NAME_CURRENT
              valueFrom:
                  fieldRef: {fieldPath: metadata.name} # 获取当前的Pod实例名
          # 修改容器地址
          image: registry.cn-hangzhou.aliyuncs.com/siegrain/name-api:1.1
          ports: 
          - containerPort: 80
          imagePullPolicy: Always
      # 1. 创建 secret
      # kubectl create secret docker-registry aliyunimagesecret --docker-server=registry.cn-hangzhou.aliyuncs.com/siegrain/name-api --docker-username=siegrainwong@gmail.com --docker-password=Weck1000232 --docker-email=siegrainwong@gmail.com
      # 2. 登录
      # docker login --username=siegrainwong@gmail.com registry.cn-hangzhou.aliyuncs.com
      # 3. 重新打tag
      # docker tag siegrainwong/name-api:1.1 registry.cn-hangzhou.aliyuncs.com/siegrain/name-api:1.1
      # 4. 推送
      # docker push registry.cn-hangzhou.aliyuncs.com/siegrain/name-api:1.1
      imagePullSecrets:
        - name: aliyunimagesecret # 这个必须小写
---

kind: Service
apiVersion: v1
metadata:
  name: name-service
  namespace: netcore
spec: 
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
  selector:
    name: name-api