# 在 netcore 命名空间基于 hostPath 挂载方式部署 Mysql

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: netcore
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30333 # 指定IP
  selector:
    app: mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: netcore
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts: # 配置挂载路径
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:  # 配置 hostPath
      - name: mysql-persistent-storage
        hostPath:
          path: /var/lib/mysql